restartPolicy: Never

githubReleaseMonitor:
  url: https://github.com/CVEProject/cvelistV5/releases
  monitorFrom: "2024-07-25"
  containerName: github-release-container
  image:
    repository: nexflare73/webapp-cve-processor
    tag: latest
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

# The imagePullSecrets is a array and key is the name of the secret and value is the base64 encoded dockerconfigjson
imagePullSecrets: {}

kafka:
  username: ""
  password: ""
  bootstrapServers: ""
  groupId: cve-consumer-group
  topic: cve-data-push
  mechanism: "PLAIN"
  maxBatchSize: 3048576
  batchTimeout: 2

controllerManager:
  namespace: "operator"
  image:
    repository: nexflare73/cve-operator
    tag: latest
  replicas: 1
  containerName: 
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8081
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8081
    initialDelaySeconds: 5
    periodSeconds: 10
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
