---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "helm-cve-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: cve-operator-controller-manager
  namespace: {{ .Values.controllerManager.namespace }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: {{ .Values.controllerManager.containerName | default "manager" }}
      labels:
        control-plane: controller-manager
    spec:
      imagePullSecrets:
        {{- include "helm-cve-operator.imagePullSecrets" . | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: control-plane
                  operator: In
                  values:
                  - controller-manager
              topologyKey: topology.kubernetes.io/zone
      containers:
      - image: "{{ .Values.controllerManager.image.repository }}:{{ .Values.controllerManager.image.tag }}"
        name: {{ .Values.controllerManager.containerName | default "manager" }}
        args:
        - --metrics-bind-address=:8443
        - --leader-elect
        - --health-probe-bind-address=:8081
        command:
        - /manager
        {{- if .Values.controllerManager.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.controllerManager.livenessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.controllerManager.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.controllerManager.readinessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.controllerManager.resources }}
        resources:
          {{- toYaml .Values.controllerManager.resources | nindent 12 }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cve-operator-controller-manager
      terminationGracePeriodSeconds: 10
