apiVersion: github.csye7125.team05/v1
kind: GithubReleaseMonitor
metadata:
  labels:
    {{- include "helm-cve-operator.labels" . | nindent 4 }}
  name: githubreleasemonitor
spec:
  url: {{ .Values.githubReleaseMonitor.url }}
  monitorFrom: {{ .Values.githubReleaseMonitor.monitorFrom | quote }}
  githubReleaseTemplate:
    jobTemplate:
      spec:
        template:
          spec:
            imagePullSecrets:
              {{- include "helm-cve-operator.imagePullSecrets" . | nindent 14 }}
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                      - key: app.kubernetes.io/jobName
                        operator: In
                        values:
                        - github-release-job
                    topologyKey: topology.kubernetes.io/zone
            containers:
              - name: {{ .Values.githubReleaseMonitor.containerName }}
                image: "{{ .Values.githubReleaseMonitor.image.repository }}:{{ .Values.githubReleaseMonitor.image.tag }}"
                env:
                  - name: KAFKA_BROKER
                    valueFrom:
                      configMapKeyRef:
                        name: kafka-producer-config
                        key: kafkaHost
                  - name: KAFKA_TOPIC
                    valueFrom:
                      configMapKeyRef:
                        name: kafka-producer-config
                        key: topic
                  - name: KAFKA_USERNAME
                    valueFrom:
                      configMapKeyRef:
                        name: kafka-producer-config
                        key: username
                  - name: KAFKA_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: kafka-credentials
                        key: password
                  - name: SASL_MECHANISM
                    valueFrom:
                      configMapKeyRef:
                        name: kafka-producer-config
                        key: mechanism
                  - name: BATCH_TIMEOUT
                    valueFrom:
                      configMapKeyRef:
                        name: kafka-producer-config
                        key: batchTimeout
                  - name: MAX_BATCH_SIZE
                    valueFrom:
                      configMapKeyRef:
                        name: kafka-producer-config
                        key: maxBatchSize
                {{- if .Values.githubReleaseMonitor.resources }}
                resources:
                  {{- toYaml .Values.githubReleaseMonitor.resources | nindent 18 }}
                {{- end }}
            restartPolicy: {{ .Values.restartPolicy | default "Never" }}
