{{- if .Values.controllerManager.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    {{- include "helm-cve-operator.labels" . | nindent 4 }}
  name: cve-operator-controller-manager-hpa
  namespace: {{ .Values.controllerManager.namespace }}
spec:
  maxReplicas: {{ .Values.controllerManager.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.controllerManager.autoscaling.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cve-operator-controller-manager
  metrics:
    {{- if .Values.controllerManager.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.controllerManager.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.controllerManager.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.controllerManager.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}