---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "helm-cve-operator.labels" . | nindent 4 }}
  name: cve-operator-leader-election-role
  namespace: {{ .Values.controllerManager.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "helm-cve-operator.labels" . | nindent 4 }}
  name: cve-operator-githubrelease-editor-role
rules:
- apiGroups:
  - github.csye7125.team05
  - batch
  resources:
  - githubreleases
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.csye7125.team05
  - batch
  resources:
  - githubreleases/status
  - jobs
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "helm-cve-operator.labels" . | nindent 4 }}
  name: cve-operator-githubrelease-viewer-role
rules:
- apiGroups:
  - github.csye7125.team05
  - batch
  resources:
  - githubreleases
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.csye7125.team05
  - batch
  resources:
  - githubreleases/status
  - jobs
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "helm-cve-operator.labels" . | nindent 4 }}
  name: cve-operator-githubreleasemonitor-editor-role
rules:
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleasemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleasemonitors/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "helm-cve-operator.labels" . | nindent 4 }}
  name: cve-operator-githubreleasemonitor-viewer-role
rules:
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleasemonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleasemonitors/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "helm-cve-operator.labels" . | nindent 4 }}
  name: cve-operator-manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleasemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleasemonitors/finalizers
  verbs:
  - update
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleasemonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleases/finalizers
  verbs:
  - update
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleases/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "helm-cve-operator.labels" . | nindent 4 }}
  name: cve-operator-metrics-auth-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "helm-cve-operator.labels" . | nindent 4 }}
  name: cve-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get