{{- range $name := keys .Values.imagePullSecrets }}
apiVersion: v1
data:
  .dockerconfigjson: {{ get $.Values.imagePullSecrets $name }}
kind: Secret
metadata:
  name: {{ $name | quote }}
  labels:
    {{- include "helm-cve-operator.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
{{- end }}

---
{{- range $name := keys .Values.imagePullSecrets }}
apiVersion: v1
data:
  .dockerconfigjson: {{ get $.Values.imagePullSecrets $name }}
kind: Secret
metadata:
  name: {{ $name | quote }}
  namespace: {{ $.Values.controllerManager.namespace }}
  labels:
    {{- include "helm-cve-operator.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
type: Opaque
data:
  password: {{ .Values.kafka.password | b64enc | quote }}