---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "helm-cve-operator.labels" . | nindent 4 }}
  name: cve-operator-controller-manager
  namespace: {{ .Values.controllerManager.namespace }}