---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "helm-cve-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: cve-operator-controller-manager-metrics-service
  namespace: {{ .Values.controllerManager.namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager